### ISSUE TITLE
How to support instant queries

### ISSUE THREAD

**Issue by nicolastakashi** [perses/perses#1151]
Given Perses is looking to have a core table panel #1143, would be amazing to have the ability to run instant queries using the PrometheusPlugin.

As we discussed on the matrix, the main idea is to provide this through a new plugin kind named `PrometheusInstantQuery`

On the UI we can initially have this as another Option on the `query type` dropdown, but maybe in the future would be better abstract the plugin selection from the user through a check box between Instant and Range Queries.

**Comment by sjcobb** [comment]
There were some good points raised on Matrix and I tried to summarize our discussion on Mon [here](https://github.com/perses/perses/discussions/947?sort=new#discussioncomment-5839960)

Some key takeaways I had are: 
- how do we make the UX around single datapoint visualizations more explicit (ex: if `calculation` is an option in the panel spec, it should be disabled)
- we need Shan’s proposed `supportedQueryInterfaces` before we can take this on
  - since this new query plugin should not be in TimeSeriesChart’s `supportedQueryInterfaces`

**Comment by sjcobb** [comment]
So maybe this isn’t the best first task for a new contributor to take on since `supportedQueryInterfaces` doesn’t exist yet unfortunately. 

For context, the best summary of the proposal is [here](https://github.com/perses/perses/pull/922#discussion_r1080546854) and we alluded to it in #956

**Comment by nicolastakashi** [comment]
I'm going to close this issue, since it was a question and I'll open a new one to follow the implementation.
#1456
