### ISSUE TITLE
Query editor error can cause panel preview to be unresponsive 

### ISSUE THREAD

**Issue by sjcobb** [perses/perses#1342]
Input invalid PromQL into our panel edit drawer query editor. A nice error message shows in the panel preview but fixing the query will not update the chart. Error remains in preview until you discard panel and start over. 

Need to adjust Error Boundaries and check if specUpdated conditions or onBlur behavior is broken 

Client-side query truncation will be needed in the future to improve this editor experience (since heavy queries can stall or crash browser tab). A future PromLens integration will also be important to look into to help users fix/understand their queries

**Comment by AntoineThebaud** [comment]
NB the issue is occurring when you have only 1 query defined in the panel. If you have 2+ queries and one has invalid syntax, it just won't get displayed, without any error showing.
Thus there are room for another improvement here, as it would be good to display explicitly what's wrong with the query (e.g just aside/below the query editor)
