### ISSUE TITLE
Change variable syntax from $myVar to ${myVar} 

### ISSUE THREAD

**Issue by celian-garcia** [perses/perses#1345]
To better know the end of a variable in a text.

Ex: up{node=~"${prefix}something.*"}

**Comment by Gladorme** [comment]
The problem with the actual format is the following:
You create a variable `$test` and `$test1`. When the variable `$test1` is parsed, it will parse `$test` instead

**Comment by Gladorme** [comment]
MB, it's working as intended. It's failed when I test because I used a dot in the second varaible. And the [regex](https://github.com/perses/perses/blob/3a637aae1eafcd3d24e4f8ff7a3c5e8b6c971d9e/ui/plugin-system/src/utils/variables.ts#L49) do no support dot.
The validation is not aligned on the front or on the back 😄

**Comment by celian-garcia** [comment]
Still I personally find it more readable with curly braces.
