### ISSUE TITLE
Edit global datasource name if default

### ISSUE THREAD

**Issue by celian-garcia** [perses/perses#1356]
When we edit the datasource name it is doing a create + delete actions. 
But if it is default, then we create a second default which is not authorized.
![image](https://github.com/perses/perses/assets/10258608/ce7e0322-5455-4dee-83c1-fdee507017b9)

**Comment by AntoineThebaud** [comment]
oops, didnt think about that one..

An easy win with the current implem would be to just swap the create & delete actions

**Comment by Gladorme** [comment]
If the delete pass and the creation fail, you will have the same issue. Not a huge fan of this solution 😕

**Comment by celian-garcia** [comment]
Solutions are simple:
Either we make sure the delete is not done if the create didn't succeed => Would make it impossible to rename a default datasource
Or we don't propose the feature. 

I am ok with first but it needs to be explicit in for the user in the form => frontend form validation topic

**Comment by AntoineThebaud** [comment]
> If the delete pass and the creation fail, you will have the same issue (datasource deleted). Not a huge fan of this solution 😕

This is actually a different issue & a known risk of the current dirty implementation (you could already have only one of the actions succeeding). Swapping to have delete then create would change nothing to that but would at least prevent this situation where you are trying to create a default datasource while there's one already.

Besides yes this part of the code requires a real rework, we already discussed some alternatives here https://github.com/perses/perses/pull/1267#discussion_r1253721757

**Comment by Nexucis** [comment]
I'm fine on my side to drop the feature for the moment and to take time to think of a safe solution if there is one, because we shouldn't do it only for the datasource but for every resources (just to be consistent)

**Comment by celian-garcia** [comment]
> > If the delete pass and the creation fail, you will have the same issue (datasource deleted). Not a huge fan of this solution confused
> 
> This is actually a different issue & a known risk of the current dirty implementation (you could already have only one of the actions succeeding). Swapping to have delete then create would change nothing to that but would at least prevent this situation where you are trying to create a default datasource while there's one already.
> 
> Besides yes this part of the code requires a real rework, we already discussed some alternatives here [#1267 (comment)](https://github.com/perses/perses/pull/1267#discussion_r1253721757)

I'd disagree on the fact that the order is not important. 
- delete + create, if create fails you loose information
- create + delete, if create fails the delete should just not be executed. this is all the problem. 

I would keep the feature but just don't execute the subsequent delete if create fails.

**Comment by Nexucis** [comment]
create cannot be executed when it is a default datasource, because you cannot have two default datasource for the same type of datasource. So the way it is actually managed doesn't work.

**Comment by AntoineThebaud** [comment]
I don't know why you keep intricating a second/different issue with the one being discussed here :D

> create cannot be executed when it is a default datasource, because you cannot have two default datasource for the same type of datasource. So the way it is actually managed doesn't work.

Exactly, and given original post let's agree this is the issue being discussed here. In this regard, swapping the operations to have delete then create would solve it, but I think we agree this is the worst way to solve it. @celian-garcia I didn't say the order is not important and yes you're right that changing the order makes it more risky, still if we have for the moment no time to do better than this I think it's better doing this than dropping the feature.

> because we shouldn't do it only for the datasource but for every resources (just to be consistent)

Ideally yes, but imho this ability to rename has not the same importance between each resource. I did this quick & dirty way for the datasources, but I think this is especially important for the variables (not done yet!) since the "technical" name is used broadly (in all the queries), while for e.g datasources & dashboards users are more likely to deal with their display name. So given this it's okay to not have the same prio among all resources.

Anyway talking about proper solutions (https://github.com/perses/perses/pull/1267#discussion_r1253721757) I think that the easiest & clean solution is this one already discussed:

> Add a "duplicate" action, which allow you to replicate an existing var, just changing its name. Then you're free to delete the original one.

-> Note that regarding the issue discussed here, the duplicate should thus not have the default flag ticked & you should manually set it after you delete the original datasource. So this solution remains a workaround and on paper the real solution is more likely to be:

> Add a new ID attribute to the datamodel, and make it the primary key, auto managed/incremented by the backend.

@Nexucis can you shed some light here?
> I'm lacking context (or memories...) here on why such ID/UID attribute was not put in the data model of the various Perses objects - this would have been a clean way to avoid this tricky case for sure ^^.

**Comment by celian-garcia** [comment]
Regarding the issue that I posted here. I will do a quick win that will be to prevent from doing the delete if the create fails. To me this is really the simplest for now. The 400 error message is clear enough then for the user to understand what happens.

For deeper discussion regarding how we propose the renaming (or not) generally in the front, let's create a dedicated discussion.

**Comment by AntoineThebaud** [comment]
Recap of the live discussion we just had about this:
- We decided to drop the rename feature for now, waiting any user request/complaint to bring back the subject. PR to be done in a near future (this issue can be closed afterwards).
- We agreed on the fact to implement a duplicate action to somehow work around this impossibility to rename. To be implemented for datasources & variables. Could be considered for dashboards to. However regarding projects we think this is a bad idea (would require to deep copy all the objects contained), thus we'd need to find another solution for project renaming.
- About why we have no UID in the datamodel: this is to follow the Kubernetes way & be CRD ready. With kubernetes the access to resources either via URLs or CLI commands is done by referencing their names, so we want to use the name as ID to reproduce the same in Perses.
