### ISSUE TITLE
Project API requests are not case sensitive

### ISSUE THREAD

**Issue by Gladorme** [perses/perses#1420]
### What did you do?

Create projects: "perses" and add dashboard in the project. Migrate a dashboard and set "Perses" as project name.

### What did you expect to see?

Only see "perses" dashboards when requesting API `/api/v1/projects/perses/dashboards`

### What did you see instead? Under which circumstances?

"perses" and "Perses" dashboards when requesting API `/api/v1/projects/perses/dashboards`

**Comment by Gladorme** [comment]
Variables & datasources are probably concerned too (not checked)

**Comment by Nexucis** [comment]
Looks like the issue is coming when you are using the file system as a DB and it also depends on which OS you are.

On a MacOS, it's not possible to create different file `Foo`, `foo`. At the end there is only one file existing on the file system.

The question would be more should we allow this behaviour. It will be probably annoying to have different projects with the same name but with different cases. Like `FOO`, `FoO`, `fOo`, `foo`,`Foo`

Note: To reproduce the issue described above, 
1. You need to use the file system as a DB
2. You need to be on a MacOS
3. you need to migrate a dashboard and then instead of choosing the project `perses`, you choose the project `Perses`. 

It will work on a macOS because the query that verify if the project exists is case insensitive. But now when you are querying the dashboards, you will think it's coming from two different projects. Which is of course not the case.
