### ISSUE TITLE
OIDC clientID Only Flow Support

### ISSUE THREAD

**Issue by rasmusvan** [perses/perses#2172]
### Proposal

Currently in the Perses configuration, client_secret is a mandatory field. This is excessive and should be made into an optional field, considering there are flows that only require clientID

**Comment by Nexucis** [comment]
yes indeed.
Would you like to make the changes ?

**Comment by celian-garcia** [comment]
That's interesting, I didn't know that because the lib asked for a secret parameter but that's true :slightly_smiling_face: 
Indeed feel free to propose a PR if it's important for you. 

As I did a bit of research I drop that here 
- oauth2.0 doesn't require a secret in authorization + access token requests 
  https://www.rfc-editor.org/rfc/rfc6749#section-4.1.1
  https://www.rfc-editor.org/rfc/rfc6749#section-4.1.3
- oidc neither
  https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest
  https://openid.net/specs/openid-connect-core-1_0.html#TokenRequest

**Comment by Nexucis** [comment]
fix with https://github.com/perses/perses/pull/2296
