### ISSUE TITLE
Distributed tracing dashboard / Gantt chart

### ISSUE THREAD

**Issue by pavolloffay** [perses/perses#978]
Hello, first thanks for the awesome initiative. 

I would like to explore the possibility if the perses project will provide any distributed tracing visualization capabilities - e.g. trace search and Gantt chart/timeline view. 

![Screenshot of Jaeger UI](https://user-images.githubusercontent.com/5618424/220687660-00485526-c77d-45ed-8dbb-5480131d05bb.jpg)

**Comment by Nexucis** [comment]
Hello :)

Thank you for your kind words !

Yes that's something we want to support in Perses at some point !

**Comment by Nexucis** [comment]
so if you want to explore this possibility, please go ahead :). Nobody is working currently on it for the moment.

**Comment by sjcobb** [comment]
For integrating with dashboards, issue #1303 will be a prerequisite so that a TraceQuery plugin can be added and used for specific panels when it’s included in `supportedQueryInterfaces`

Adding data links / ability to navigate from a pinned tooltip or context menu will also be interesting to explore in the future

**Comment by Nexucis** [comment]
this has been tackled thanks to @zhuje hard work. I think we can close it now :)
